# Generated by Django 4.1.4 on 2022-12-23 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalist',
            name='Timezone',
        ),
    ]
