# Generated by Django 4.1.4 on 2022-12-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_datalist_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktime',
            name='Slotcount',
        ),
    ]
