# Generated by Django 4.1.3 on 2022-12-23 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_booktime_slotcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktime',
            name='CoachName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='data.datalist'),
        ),
    ]
