# Generated by Django 4.1.3 on 2022-12-23 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_booktime_coachname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktime',
            name='SlotperiodTo',
        ),
    ]
