# Generated by Django 4.1.4 on 2022-12-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_remove_booktime_slotperiodto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktime',
            name='Slotperiodfrom',
            field=models.TimeField(default=None),
        ),
    ]
