# Generated by Django 4.1.4 on 2022-12-23 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datalist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CoachName', models.CharField(max_length=100)),
                ('Timezone', models.DateTimeField()),
                ('Day', models.CharField(max_length=20)),
                ('TotalSlotFrom', models.TimeField()),
                ('TotalSlotuntil', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Booktime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slotcount', models.IntegerField()),
                ('Slotperiodfrom', models.TimeField()),
                ('SlotperiodTo', models.TimeField()),
                ('CoachName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.datalist')),
            ],
        ),
    ]
