# Generated by Django 4.1.4 on 2022-12-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booktime',
        ),
        migrations.DeleteModel(
            name='datalist',
        ),
    ]
